server:
  port: 9090
#  port: 8080

spring:
  application:
    name: pagepalette
  jpa:
    hibernate:
      ddl-auto:  update
    properties:
      hibernate:
         show_sql: true
#        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pagepalette?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 123456
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
management:
  endpoints:
    web:
      exposure:
        include: "*"
cors:
  enabled: true
  allowed-origins: http://localhost:3000,https://localhost:3000,https://i8b103.p.ssafy.io/
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: auth
